### PR TITLE
Closes #99: Make logging configurable.

### LINKED ISSUE #99: Prune logging cannot be set
## Bug Report

**What did you do?**

Wanting to [configure the Prune structure](https://sdk.operatorframework.io/docs/best-practices/resource-pruning/#operator-lib-prune-library) but the [log field](https://github.com/operator-framework/operator-lib/blob/main/prune/prune.go#L73) is not exported and never set.

**What did you expect to see?**

Either that the field is automatically populated or that it is exported.

**What did you see instead? Under which circumstances?**

A field that is not exported and not automatically set.

**Possible Solution**

Although, I am not in favor of using global variables for loggers things should be consistent inside a library. The other features provided by operator-lib for instance [event handler](https://github.com/operator-framework/operator-lib/blob/main/handler/enqueue_annotation.go#L32) and [leader election](https://github.com/operator-framework/operator-lib/blob/main/leader/leader.go#L43) use a preset variable:
~~~
var log = logf.Log.WithName("event_handler")
var log = logf.Log.WithName("leader")
~~~

logf is a package of the controller-runtime library, which contains logr.Logger Log. This assumes that SetLogger was called earlier, which is the same expectation sets by Kubebuilder/controller-runtime. 
This makes this library less suitable for clients or other apps not based on controller-runtime but again things should be consistent.

Another thing I would like to mention and a second issue could get open for it is that the naming/structure could be improved. It seems a bit unconventional to have a method like Execute on a structure named Config. I would expect that more on a structure called Pruner. Config being what is provided by users to get Pruners that fits their needs.

### PR DESCRIPTION
**Pull request by fgiloux**
**Description of the change:**

Closes #99
This pull request aligns the logging configuration in the prune feature with what is done in the rest of the library. It declares a package level variable for a logger. The logger is retrieved from the controller-runtime library, which is leveraging logr.

**Motivation for the change:**

The current prune implementation could not be used outside of the prune package as the log field of the Config struct was unexported.

A pull request for amending the documentation will follow.

### CODE REVIEW

**Comment by fgiloux** [comment]
cc @camilamacedo86 @Sijoma @ryantking

**Comment by fgiloux** [comment]
@camilamacedo86 can you please review the PR?

**Review by camilamacedo86 — COMMENTED** [review]
/lgtm

**Review by camilamacedo86 — APPROVED** [review]

**Comment by fgiloux** [comment]
@theishshah @varshaprasad96 Anything preventing the merge of this PR?

**Comment by joelanford** [comment]
@fgiloux I made [this comment](https://github.com/operator-framework/operator-lib/issues/99#issuecomment-1074145194) over on the issue. WDYT?

**Comment by fgiloux** [comment]
@joelanford @varshaprasad96 @camilamacedo86 reworked to address Joe's concerns

File: prune/prune.go [hunk 1]
```diff
@@ -181,3 +181,17 @@ func (config Config) validate() (err error) {
 	}
 	return nil
 }
+
+// Logger returns a logger from the context using logr method or Config.Log if none is found
+// controller-runtime automatically provides a logger in context.Context.
+// Note that there is no compile time check whether a logger can be retrieved by either way.
+// keysAndValues allow to add fields to the logs, cf logr documentation.
+func Logger(ctx context.Context, cfg Config, keysAndValues ...interface{}) logr.Logger {
+	log := cfg.Log
```
Comment (joelanford) [inline prune/prune.go:190]: I kind of feel like `cfg.Log` (if it's set) should win over `logr.FromContext()`. WDYT?

File: prune/prune.go [hunk 2]
```diff
@@ -181,3 +181,17 @@ func (config Config) validate() (err error) {
...
+	if ctx != nil {
+		if logger, err := logr.FromContext(ctx); err == nil {
```
Comment (joelanford) [inline prune/prune.go:192]: Should we use controller-runtime's version of this function so that if there isn't a logger in the context, we end up with the controller-runtime's global logger? Or is that too much coupling to controller-runtime?

File: prune/prune.go [hunk 3]
```diff
@@ -181,3 +181,17 @@ func (config Config) validate() (err error) {
 	}
 	return nil
 }
+
+// Logger returns a logger from the context using logr method or Config.Log if none is found
+// controller-runtime automatically provides a logger in context.Context.
```
Comment (joelanford) [inline prune/prune.go:186]:
```suggestion
// controller-runtime automatically provides a logger in context.Context during Reconcile calls.
```
Maybe other times as well? This is the only one I know about though.

File: prune/prune.go [hunk 4]
```diff
@@ -181,3 +181,17 @@ func (config Config) validate() (err error) {
...
+// Note that there is no compile time check whether a logger can be retrieved by either way.
+// keysAndValues allow to add fields to the logs, cf logr documentation.
+func Logger(ctx context.Context, cfg Config, keysAndValues ...interface{}) logr.Logger {
```
Comment (joelanford) [inline prune/prune.go:189]: Does this function need to be exported?

File: prune/prune.go (hunk 1 above)
Comment (fgiloux) [reply prune/prune.go:190]: My thinking was that cfg.Log is set once whereas logr.FromContext() can be changed, although unlikely with every request. I picked the one with the scope having the shorter lifetime

File: prune/prune.go (hunk 2 above)
Comment (fgiloux) [reply prune/prune.go:192]: My thinking was to avoid coupling with controller-runtime... but the library has already a dependency on controller-runtime. I think Jeff wanted to make it available to other frameworks, hence 
~~~
type Config struct {
        Clientset      kubernetes.Interface      // kube client used by pruning
~~~
Due to the already existing dependency I can use the controller-runtime version

File: prune/prune.go (hunk 3 above)
Comment (fgiloux) [reply prune/prune.go:186]: I won't debate on that :-)

File: prune/prune.go (hunk 4 above)
Comment (fgiloux) [reply prune/prune.go:189]: It is exported in controller-runtime and the user can leverage it for custom code that gets injected through PreDeleteHook and CustomStrategy. I am passing the context to them for the purpose.

File: prune/prune.go (hunk 2 above)
Comment (fgiloux) [reply prune/prune.go:192]: This also means that we will always get a logger from context. In that case this cannot have precedence over the logger set in the config struct otherwise this would never be set.

File: prune/prune.go (hunk 1 above)
Comment (joelanford) [reply prune/prune.go]: My thought was that if I go to the trouble of setting the logger in the config, that's an extra explicit step I'm taking to say "use this logger". With the code as is, if I was using this in `Reconcile`, I'd have to create a new context that drops the logger from the Reconcile context before using the prune functions. That seems pretty awkward.

File: prune/prune.go (hunk 4 above)
Comment (joelanford) [reply prune/prune.go:191]: Got it. Makes sense. Thanks for the explanation!

**Comment by camilamacedo86** [comment]
Hi @joelanford @jmrodri @varshaprasad96 

This project still < 1.0.0, any reason for we do not move forward when the api diff fails?
Do we need to ensure backwords compatibility in the lib?

**Comment by joelanford** [comment]
Do we know what the impact would be if this broke (what change is necessary for callers?, how many operators are using the library?). I'd say its okay to break this if necessary, but we should generally try to avoid it. 

Did someone mention that @ryantking had a larger design or some follow-on changes to make? If so, I'd suggest that we try to avoid breaking these APIs twice.

**Comment by fgiloux** [comment]
@camilamacedo86 @joelanford as per #99 the current situation is that Config.log is not exported and not set automatically but it is [called in the code](https://github.com/operator-framework/operator-lib/blob/main/prune/maxcount.go#L35). In my opinion this makes the library broken. Hence there is nothing to break. As the prune library is documented in multiple places the urgency is to make it usable That's the aim of this PR.
To answer Joe''s questions:

> Do we know what the impact would be if this broke (what change is necessary for callers?

No impact, adding a field, which is optional is not breaking an API. This means if the library had happened to work it would work further but it did not by any way.

> how many operators are using the library?). I'd say its okay to break this if necessary, but we should generally try to avoid it.

As log is called and not configurable my guess would be exactly 0.

> Did someone mention that @ryantking had a larger design or some follow-on changes to make? If so, I'd suggest that we try to avoid breaking these APIs twice.

I mentioned that. The [EP](https://github.com/operator-framework/enhancements/pull/109) has been however stale waiting to get merged for months. The urgency is to make a documented library usable.

**Comment by joelanford** [comment]
Seems like the breaking change is adding a context parameter to the PreDelete and StrategyFunc function signatures.

Based on everything @fgiloux said, it seems like a no brainer to get this library to a working state even if that means some minor breaking API changes.

/lgtm
